---
title: "Superior Visualizations"
author: "Wilson Neddo"
keep-md: true
---

```{r, warning=FALSE, message=FALSE}
library(DT)
library(pander)
library(tidyverse)
library(tidyr)
library(tidyquant)
library(ggplot2)
library(lattice)
library(readr)
library(dplyr)
library(stringi)
library(tidytext)
library(readxl)
library(rio)
library(stringr)
library(haven)
library(ggrepel)
library(ggthemes)
library(directlabels)
library(plotly)
library(gapminder)
library(hexbin)
library(lubridate)
library(riem)
library(sf)
library(geofacet)
library(leaflet)
library(leaflet.providers)
library(leaflet.extras)
```

# Datasets
```{r}
# Natural ways Lake Superior has inflow and outflow
nat_sup <- read_excel("~/My Stat and Data Projects/Stats-Projects/My Datasets/Lake Superior Data.xlsx")

# Consumer Usage of lake
con_sup <- read_excel("~/My Stat and Data Projects/Stats-Projects/My Datasets/Sup Consumer (by year).xlsx")
```

# Merge Dataset
```{r}

```

# Visualizations

## Evaporation
```{r}
ggplot(nat_sup, aes(x=Month, y=Evaporation, color=Year))+
  geom_point(size=3)+
  geom_line(aes(group = 1)) +
  geom_smooth(method = "lm", se = TRUE) +
  ggtitle("Evaporation Of Lake Superior By Month and Year")+
  labs(x="Month of the Year", y="Evaporation by m^3/sec")
```

## Precipitation
```{r}
ggplot(nat_sup, aes(x=Month, y=Precipitation, color=Year))+
  geom_point(size=3)+
  geom_line(aes(group = 1)) +
  geom_smooth(method = "lm", se = TRUE) +
  ggtitle("Precipitation Of Lake Superior By Month and Year")+
  labs(x="Month of the Year", y="Precipitation by m^3/sec")
```

## Runoff
```{r}
ggplot(nat_sup, aes(x=Month, y=Runoff, color=Year))+
  geom_point(size=3)+
  geom_line(aes(group = 1)) +
  geom_smooth(method = "lm", se = TRUE) +
  ggtitle("Runoff Of Lake Superior By Month and Year")+
  labs(x="Month of the Year", y="Runoff by m^3/sec")
```

## Consumer Usage
```{r}
ggplot(con_sup, aes(x=Year, y=Consumer, color=Year))+
  geom_point(size=3)+
  geom_line(aes(group = 1)) +
  geom_smooth(method = "lm", se = TRUE) +
  ggtitle("Consumer Usage Of Lake Superior By Year")+
  labs(x="Month of the Year", y="Consumer Usage by ft^3")
```

## Compare All
```{r}

```

